---
title: "stats1"
author: "GUARDIA Damien"
date: "2024-03-06"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
n2000 <- read.csv("n2000.CSV", sep=";", encoding="latin1")
```
Exercice 1 ) Cela permet de préciser les caractères de séparation, et l'encoding

```{r}

plot(unlist(n2000[5]),unlist(n2000[6]))
     
library(tidyverse)
ggplot(data = n2000) +
  aes(x = long,
  y = lat,
  color=biogeo) +
  geom_point()
```

exercice 2) Il y a le numéro,  le code, le nom du site, sa surface, ces coordonnées, nbcom?, le climat, et les activités. Il y a des types int (entiers), chr (chaines de caractères), dbl (pour les nombre à virgules)


```{r}
skewness  <- function(x) {
  n <- length(x)
  mean_x <- mean(x)
  sd_x <- sd(x)
  skew <- sum((x - mean_x)^3) / (n * sd_x^3)
  return(skew)
}

kurtosis <- function(x) {
  n <- length(x)
  mean_x <- mean(x)
  sd_x <- sd(x)
  kurt <- sum((x - mean_x)^4) / (n * sd_x^4) - 3
  return(kurt)
}


n2000_apply <- sapply(n2000,is.numeric)
n2000_summary <- n2000[n2000_apply]
n2000_summary <- n2000 |>
  select(surf,long,lat,alt,nbcom,activplus,activmoins)

n2000_summary <- n2000_summary[-1]

summary_results <- lapply(n2000_summary, function(x) {c(summary(x),skewness = skewness(x),kurtosis = kurtosis(x), sd=sd(x))})

boxplot(x=unlist(summary_results[5]))

lapply(summary_results, function(x) {c(hist(x=x,breaks=4),boxplot(x=x))})

#Nous pouvons voir que les répartitions sont inégales

```
```{r}
unlisted_n2000 <- unlist(n2000);
table_n2000 <- table(unlisted_n2000)

effectif <-c(table_n2000["Alpine"],table_n2000["Atlantique"],table_n2000["Continentale"],table_n2000["Méditerranéenne"])

total_pc <- sum(effectif)/100

effreq <- df <- data.frame(
  effectifs = effectif,
  fréquences = c(table_n2000["Alpine"]/total_pc, table_n2000["Atlantique"]/total_pc, table_n2000["Continentale"]/total_pc,table_n2000["Méditerranéenne"]/total_pc)
)

s_alpine <-0
s_atlantique<-0
s_continental <- 0
s_medi<-0
longueur <- lengths(n2000[1])
for (i in 1:longueur) {
  if (n2000[i,9] == "Alpine"){
    s_alpine <- s_alpine+ n2000[i,4]
  }
  else if (n2000[i,9] == "Atlantique"){
    s_atlantique <- s_atlantique+ n2000[i,4]
  }
  else if (n2000[i,9] == "Continentale") {
    s_continental <- s_continental + n2000[i,4]
  }
  else if (n2000[i,9] == "Méditerranéenne") {
    s_medi <- s_medi + n2000[i,4]
  }
}
s_total_p<-(s_alpine+s_atlantique+s_continental+s_medi)/100

tsurface <- df <- data.frame(
  surface = c(s_alpine,s_atlantique,s_continental,s_medi),
  pourcentage = c(s_alpine/s_total_p, s_atlantique/s_total_p, s_continental/s_total_p,s_medi/s_total_p)
)
rownames(tsurface) <- c("Alpine", "Atlantique", "Continentale", "Méditerranéenne")

noms_barres <- c("Alpine", "Atlantique", "Continentale", "Méditerranéenne")


barplot(unlist(effreq[1]), horiz = TRUE, 
        names.arg = noms_barres, 
        main = "Zones N2000 selon les catégories géobiologiques",
        las = 1)

barplot(unlist(tsurface[1]), 
        names.arg = noms_barres, 
        main = "Zones N2000 selon les catégories géobiologiques",
        las = 1)

effreq_tibble <- as_tibble(effreq)
effreq_tibble <- effreq_tibble |>
  add_column( noms_barres, .before = 1)

tsurface_tibble <- as_tibble(tsurface)
tsurface_tibble <- tsurface_tibble |>
  add_column( noms_barres, .before = 1)

ggplot(data = effreq) +
 aes(x = noms_barres,
     y=effectif) +
 geom_col() 

ggplot(data = tsurface_tibble) +
 aes(x = noms_barres,
     y=surface) +
 geom_col() 

#Nous pouvons voir que les données sont relativement similaires, à part pour Atlantique, qui est plus important

```


```{r}
#pour rappel n_2000_summary est équivalent à toutes les données quantitatives de n2000 qui nous interressent,
cor(x=n2000_summary)
pairs(x=n2000_summary)

library(GGally)
ggpairs(n2000_summary)

# Faire cor.test() !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

for (i in 1:(ncol(n2000_summary) - 1)) {
  for (j in (i + 1):ncol(n2000_summary)) {
    cor.test(n2000_summary[,i], n2000_summary[,j])# on peut le print
  }
}

print("activplus et activmoins sont très liés, les autres ne le sont pas du tout.")


```

```{r}
lm(formula = n2000_summary$activmoins ~n2000_summary$activplus)

plot(x = n2000_summary$activmoins, y = n2000_summary$activplus,abline(lm(formula = n2000_summary$activmoins ~n2000_summary$activplus)))

print("Les points sont principalements autour de la droite, mais, plus la valeur est élevé, plus les points sont au dessus de la droite")

intervalles <- c(1, 3, 6, 11, 21,Inf)

n2000_summary$classes <- cut(n2000_summary$nbcom, breaks = intervalles, labels = c("1 ou 2 communes", "3 à 5 communes", "6 à 10 communes", "11 à 20 communes","21 communes ou plus"))

tcom <- table(n2000_summary$classes,n2000$biogeo)

barplot(tcom)


```